# Generated by Django 4.2.1 on 2023-05-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('TrueName', models.CharField(max_length=40)),
            ],
        ),
    ]
