# Generated by Django 4.2.1 on 2023-05-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
