# Generated by Django 4.2.1 on 2023-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendshiprequest_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='id',
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='ID',
            field=models.AutoField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
